# Generated by Django 3.1 on 2020-08-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxPostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('linuxpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linux.linuxpost')),
            ],
        ),
    ]
