# Generated by Django 3.1 on 2020-08-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0002_linuxpostview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linuxpostview',
            old_name='client_ip',
            new_name='client_ip2',
        ),
    ]
