# Generated by Django 3.1 on 2020-08-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0003_auto_20200829_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linuxpostview',
            old_name='client_ip2',
            new_name='client_ip',
        ),
    ]
