# Generated by Django 3.1 on 2020-08-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0005_auto_20200829_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinuxPostView',
        ),
    ]
