# Generated by Django 3.1 on 2020-09-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('developmentpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='development.developmentpost')),
            ],
        ),
    ]
